#############################################################################
# Makefile for building: Homework4ActualQt.app/Contents/MacOS/Homework4ActualQt
# Generated by qmake (3.1) (Qt 6.9.3)
# Project:  Homework4ActualQt.pro
# Template: app
# Command: /Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/bin/qmake -o Makefile Homework4ActualQt.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers -I../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtGui.framework/Headers -I../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Headers -I../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/macx-clang -F/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/lib
QMAKE         = /Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Homework4ActualQt1.0.0
DISTDIR = /Users/deepikadasari/Homework4ActualQt/.tmp/Homework4ActualQt1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -mmacosx-version-min=12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/lib
LIBS          = $(SUBLIBS) -F/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtNetwork -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		socialnetworkmainwindow.cpp \
		network.cpp \
		user.cpp \
		post.cpp \
		bio.cpp \
		messageFilter.cpp moc_socialnetworkmainwindow.cpp
OBJECTS       = main.o \
		socialnetworkmainwindow.o \
		network.o \
		user.o \
		post.o \
		bio.o \
		messageFilter.o \
		moc_socialnetworkmainwindow.o
DIST          = users.txt \
		posts.txt \
		bios.txt \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/spec_pre.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/device_config.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/unix.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/mac.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/macx.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/sanitize.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/gcc-base.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/gcc-base-mac.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/clang.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/clang-mac.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/qconfig.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_charts.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_core.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_designer.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_gui.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_help.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_network.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_png_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qml.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_sql.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svg.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_xml.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qt_functions.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qt_config.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/macx-clang/qmake.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/exclusive_builds.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/sdk.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/toolchain.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/toolchain.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/default_pre.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/default_pre.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/resolve_config.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/default_post.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/default_post.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/objective_c.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qml_debug.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/mac.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/warn_on.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/permissions.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qt.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/resources_functions.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/resources.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/moc.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/unix/opengl.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/uic.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/unix/thread.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qmake_use.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/file_copies.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/rez.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/testcase_targets.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/exceptions.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/yacc.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/lex.prf \
		Homework4ActualQt.pro socialnetworkmainwindow.h \
		network.h \
		user.h \
		post.h \
		bio.h \
		messageFilter.h main.cpp \
		socialnetworkmainwindow.cpp \
		network.cpp \
		user.cpp \
		post.cpp \
		bio.cpp \
		messageFilter.cpp
QMAKE_TARGET  = Homework4ActualQt
DESTDIR       = 
TARGET        = Homework4ActualQt.app/Contents/MacOS/Homework4ActualQt

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/deepikadasari/Homework4ActualQt/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/deepikadasari/Homework4ActualQt/Homework4ActualQt.pro


include /Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Homework4ActualQt.app/Contents/MacOS/Homework4ActualQt: ui_socialnetworkmainwindow.h $(OBJECTS)  
	@test -d Homework4ActualQt.app/Contents/MacOS/ || mkdir -p Homework4ActualQt.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Homework4ActualQt.pro ../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/macx-clang/qmake.conf ../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/spec_pre.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/device_config.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/unix.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/mac.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/macx.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/sanitize.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/gcc-base.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/gcc-base-mac.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/clang.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/clang-mac.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/qconfig.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_charts.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_core.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_designer.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_gui.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_help.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_network.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_png_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qml.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_sql.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svg.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_xml.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qt_functions.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qt_config.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/macx-clang/qmake.conf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/exclusive_builds.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/sdk.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/toolchain.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/toolchain.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/default_pre.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/default_pre.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/resolve_config.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/default_post.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/default_post.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/objective_c.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qml_debug.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/mac.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/warn_on.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/permissions.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qt.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/resources_functions.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/resources.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/moc.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/unix/opengl.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/uic.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/unix/thread.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qmake_use.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/file_copies.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/rez.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/testcase_targets.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/exceptions.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/yacc.prf \
		../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/lex.prf \
		Homework4ActualQt.pro \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile Homework4ActualQt.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/spec_pre.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/device_config.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/unix.conf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/mac.conf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/macx.conf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/sanitize.conf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/gcc-base.conf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/gcc-base-mac.conf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/clang.conf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/common/clang-mac.conf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/qconfig.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_freetype.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_libpng.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_ext_openxr_loader.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_charts.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_charts_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_concurrent.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_core.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_core_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_dbus.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_designer.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_designer_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_gui.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_gui_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_help.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_help_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsplatform.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsplatform_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssettings.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_linguist.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimedia.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_network.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_network_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_opengl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_png_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_printsupport.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qml.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qml_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlformat_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmeta.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlnetwork.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltest.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3d.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dxr.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quick_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickeffects.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickvectorimage.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_shadertools.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_sql.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_sql_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svg.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svg_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_testinternals_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_testlib.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_tools_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_uitools.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_widgets.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_xml.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_lib_xml_private.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qt_functions.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qt_config.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/macx-clang/qmake.conf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/exclusive_builds.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/sdk.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/toolchain.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/toolchain.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/default_pre.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/default_pre.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/resolve_config.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/default_post.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/default_post.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/objective_c.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qml_debug.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/mac.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/warn_on.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/permissions.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qt.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/resources_functions.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/resources.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/moc.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/unix/opengl.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/uic.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/unix/thread.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/qmake_use.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/file_copies.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/rez.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/mac/asset_catalogs.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/testcase_targets.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/exceptions.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/yacc.prf:
../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/features/lex.prf:
Homework4ActualQt.pro:
../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtGui.framework/Resources/QtGui.prl:
../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Homework4ActualQt.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

Homework4ActualQt.app/Contents/PkgInfo: 
	@test -d Homework4ActualQt.app/Contents || mkdir -p Homework4ActualQt.app/Contents
	@$(DEL_FILE) Homework4ActualQt.app/Contents/PkgInfo
	@echo "APPL????" > Homework4ActualQt.app/Contents/PkgInfo
Homework4ActualQt.app/Contents/Info.plist: 
	@test -d Homework4ActualQt.app/Contents || mkdir -p Homework4ActualQt.app/Contents
	@$(DEL_FILE) Homework4ActualQt.app/Contents/Info.plist
	@set -o pipefail && plutil -convert xml1 -o - ../Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.dpala.Homework4ActualQt,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.dpala.Homework4ActualQt,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Homework4ActualQt,g" -e "s,@LIBRARY@,Homework4ActualQt,g" -e "s,\$${EXECUTABLE_NAME},Homework4ActualQt,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >Homework4ActualQt.app/Contents/Info.plist

all: Makefile \
		Homework4ActualQt.app/Contents/PkgInfo \
		Homework4ActualQt.app/Contents/Info.plist Homework4ActualQt.app/Contents/MacOS/Homework4ActualQt

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents socialnetworkmainwindow.h network.h user.h post.h bio.h messageFilter.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp socialnetworkmainwindow.cpp network.cpp user.cpp post.cpp bio.cpp messageFilter.cpp $(DISTDIR)/
	$(COPY_FILE) --parents socialnetworkmainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Homework4ActualQt.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_socialnetworkmainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_socialnetworkmainwindow.cpp
moc_socialnetworkmainwindow.cpp: socialnetworkmainwindow.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		network.h \
		user.h \
		bio.h \
		post.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/QTableWidget \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/libexec/moc
	/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=16 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/mkspecs/macx-clang -I/Users/deepikadasari/Homework4ActualQt -I/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers -I/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/lib/QtGui.framework/Headers -I/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Headers -I/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/lib socialnetworkmainwindow.h -o moc_socialnetworkmainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_socialnetworkmainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_socialnetworkmainwindow.h
ui_socialnetworkmainwindow.h: socialnetworkmainwindow.ui \
		../Documents/Abhi/qtStuff/6.9.3/macos/libexec/uic
	/Users/deepikadasari/Documents/Abhi/qtStuff/6.9.3/macos/libexec/uic socialnetworkmainwindow.ui -o ui_socialnetworkmainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp socialnetworkmainwindow.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		network.h \
		user.h \
		bio.h \
		post.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/QTableWidget \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/QApplication \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

socialnetworkmainwindow.o: socialnetworkmainwindow.cpp socialnetworkmainwindow.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		network.h \
		user.h \
		bio.h \
		post.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/QTableWidget \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtWidgets.framework/Headers/qtablewidget.h \
		ui_socialnetworkmainwindow.h \
		messageFilter.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtCore.framework/Headers/QObject \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtCore.framework/Headers/qobject.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Headers/QNetworkReply \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Headers/qnetworkrequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o socialnetworkmainwindow.o socialnetworkmainwindow.cpp

network.o: network.cpp network.h \
		user.h \
		bio.h \
		post.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network.o network.cpp

user.o: user.cpp user.h \
		bio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

post.o: post.cpp post.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o post.o post.cpp

bio.o: bio.cpp bio.h \
		network.h \
		user.h \
		post.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bio.o bio.cpp

messageFilter.o: messageFilter.cpp messageFilter.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtCore.framework/Headers/QObject \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtCore.framework/Headers/qobject.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Headers/QNetworkReply \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../Documents/Abhi/qtStuff/6.9.3/macos/lib/QtNetwork.framework/Headers/qnetworkrequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o messageFilter.o messageFilter.cpp

moc_socialnetworkmainwindow.o: moc_socialnetworkmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_socialnetworkmainwindow.o moc_socialnetworkmainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Homework4ActualQt/bin || mkdir -p $(INSTALL_ROOT)/opt/Homework4ActualQt/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Homework4ActualQt/bin/Homework4ActualQt.app
	
	$(QINSTALL) Homework4ActualQt.app $(INSTALL_ROOT)/opt/Homework4ActualQt/bin/Homework4ActualQt.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Homework4ActualQt/bin/Homework4ActualQt.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Homework4ActualQt/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

